### ISSUE TITLE
是否考虑用es6或者ts来重构？

### ISSUE THREAD

**Issue by tangerren** [wolfwind521/indoor3D#4]
hello， 很高兴看到作者又重新捡起了这个**伟大**的项目，前段时间学习了一下**indoor3D**的代码，看到代码中的模块或者类都是以前的写法，不知是否有用`es6`或者`ts`重构的打算，要是有重构打算的话可以一起共同完成吗？
我已经整理了一部分，但是由于有些three的插件是不支持在`ts`中使用的，所以现在只是重构了一个大致的模块类结构，实现了图像的绘制，下一步计划把**indoor3D**用到的`three`插件做`ts`适配，完善交互功能。

**Comment by wolfwind521** [comment]
感谢关注~几年前随便写的实验项目竟然有人关注我感到非常感动！伟大实在不敢当……
由于我对js只是了解点皮毛，难免有许多低级错误和不规范写法，感谢提出宝贵意见！
我最近主要的更新集中在支持比较流行的GeoJson格式、优化2d map的代码结构，并且发布一个简易的图形界面编辑器。预计国庆期间发布一个更新版。
由于代码改动量较大，因此如果要用es6或ts重构的话，可以先等等下一版 ：P

**Comment by dyh333** [comment]
关注更细。 谢谢分享。 @wolfwind521
